#!/bin/bash
# sudo apt install texlive-extra-utils pandoc texlive-xetex texlive-fonts-recommended
today=$(date +'%Y%m%d')
file=mr-${today}.pdf
wc -w index.md
pandoc index.md -o $file --pdf-engine=xelatex --listings && \
  web $file && \
  pdfbook2 $file
